qualified_type_name: kubernetes:helm_chart
display_name: Helm Chart

sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}


properties:
  Chart:
    type: string
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - classifications:
              - cluster
              - kubernetes
  Repo:
    type: string
  Directory:
    type: string
  Version:
    type: string
  Namespace:
    type: string
  Values:
    type: map(string,any)
  Internal:
    type: bool

classification:
  is:
    - kubernetes
    - helm
    - chart

delete_context:
  requires_no_upstream: true
views:
  dataflow: big
