qualified_type_name: aws:ecs_service
display_name: ECS Service

properties:
  AssignPublicIp:
    type: bool
    default_value: false
    description: Indicates whether the task's elastic network interface receives a
      public IP address
  Cluster:
    type: resource(aws:ecs_cluster)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:ecs_cluster
    description: The Amazon ECS cluster to which the service is to be deployed
  DeploymentCircuitBreaker:
    type: map
    properties:
      Enable:
        type: bool
      Rollback:
        type: bool
  DesiredCount:
    type: int
    default_value: 1
    description: The number of instantiations of the specified task definition to
      keep running on the service
  ForceNewDeployment:
    type: bool
    default_value: true
    description: Specifies whether to force a new deployment of the service
  LaunchType:
    type: string
    default_value: FARGATE
    description: The launch type on which to run your service
  LoadBalancers:
    type: list(map)
    properties:
      TargetGroup:
        type: resource(aws:target_group)
      ContainerName:
        type: string
      ContainerPort:
        type: int
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
    description: The security groups associated with the task or service
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      step:
        direction: downstream
        num_needed: 2
        resources:
          - selector: aws:subnet
            properties:
              Type: private
          - aws:subnet
    description: The subnets associated with the task or service
  TaskDefinition:
    type: resource(aws:ecs_task_definition)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:ecs_task_definition:{{ .Self.Name }}
        unique: true

    description: The family and revision (family:revision) or full Amazon Resource
      Name (ARN) of the task definition to run in the service
consumption:
  consumed:
    - model: EnvironmentVariables
      property_path: ContainerDefinitions[0].Environment
      resource: '{{ fieldValue "TaskDefinition" .Self }}'
      converter: |
        [
        {{ $i := 0}}
        {{ range $key, $value := . }}
          {
            "Name": "{{ $key }}",
            "Value": "{{ $value }}"
          }{{if ne $i (sub (len $) 1)}},{{end}}{{ $i = add $i 1 }}
        {{ end }}
        ]
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_ECS_SERVICE_NAME': '{{ .Self.Name }}'

path_satisfaction:
  as_target:
    - network
    - service_endpoint
  as_source:
    - network#Subnets

classification:
  is:
    - compute
    - container
    - long_running

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
views:
  dataflow: big
