qualified_type_name: aws:rds_instance
display_name: RDS Instance
sanitize_name:
  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  # Identifiers have these naming constraints:
  # - Must contain 1–63 alphanumeric characters or hyphens.
  # - First character must be a letter.
  # - Can't end with a hyphen or contain two consecutive hyphens.
  # - Must be unique for all DB instances per AWS account, per AWS Region.
  |
  {{ . 
    | replace `^[^[:alpha:]]+` "" 
    | replace `--+` "-" 
    | replace `-$` ""
    | replace `[^[:alnum:]-]+` "-"
    | length 1 63
  }}

properties:
  SubnetGroup:
    type: resource(aws:rds_subnet_group)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:rds_subnet_group
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
  DatabaseName:
    type: string
    default_value: main
    sanitize: |
      {{ . 
        | replace `^[^[:alpha:]]+` "" 
        | replace `--+` "-" 
        | replace `-$` ""
        | replace `[^[:alnum:]-]+` "-"
        | length 1 63
      }}  
  IamDatabaseAuthenticationEnabled:
    type: bool
    default_value: true
  Username:
    type: string
    configuration_disabled: true
  Password:
    type: string
    configuration_disabled: true
  Engine:
    type: string
    default_value: postgres
    allowed_values:
      - postgres
      - mysql
      - aurora-postgresql
      - aurora-mysql
      - aurora-postgresql
      - mariadb
      - oracle-ee
      - oracle-ee-cdb
      - oracle-se2
      - oracle-se2-cdb
      - custom-oracle-ee
      - custom-oracle-ee-cdb
      - custom-sqlserver-ee
      - custom-sqlserver-se
      - custom-sqlserver-web
      - sqlserver-ee
      - sqlserver-ex
      - sqlserver-se
      - sqlserver-web
  EngineVersion:
    type: string
    default_value: '13.7'
  InstanceClass:
    type: string
    default_value: db.t3.micro
  SkipFinalSnapshot:
    type: bool
    default_value: true
  AllocatedStorage:
    type: int
    default_value: 20
  CredentialsSecretValue:
    type: string
    configuration_disabled: true
    deploy_time: true
  RdsConnectionArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  ConnectionString:
    type: string
    configuration_disabled: true
    deploy_time: true
  Endpoint:
    type: string
    configuration_disabled: true
    deploy_time: true
  Host:
    type: string
    configuration_disabled: true
    deploy_time: true
  Port:
    type: string
    configuration_disabled: true
    deploy_time: true

consumption:
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_RDS_ENDPOINT': '{{ fieldRef "Endpoint" .Self }}'
        '{{ .Self.Name }}_RDS_CONNECTION_ARN': '{{ fieldRef "RdsConnectionArn" .Self }}'
        '{{ .Self.Name }}_RDS_USERNAME': '{{ fieldRef "Username" .Self }}'
        '{{ .Self.Name }}_RDS_PASSWORD': '{{ fieldRef "Password" .Self }}'

classification:
  is:
    - storage
    - sql
    - database
    - relational

path_satisfaction:
  as_target:
    - network
    - permissions

delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
views:
  dataflow: big
