source: aws:api_deployment
target: aws:rest_api
always_process: true
operational_rules:
  - if: '{{ hasDownstream "aws:api_integration" .Target }}'
    steps:
      - resource: '{{ .Source }}'
        direction: downstream
        resources:
          - '{{ allDownstream "aws:api_integration" .Target}}'
        num_needed: -1
  - if: '{{ hasDownstream "aws:api_method" .Target }}'
    steps:
      - resource: '{{ .Source }}'
        direction: downstream
        resources:
          - '{{ allDownstream "aws:api_method" .Target}}'
        num_needed: -1
